### ISSUE TITLE
Error when calling 'vnc.removeBackButton(viewName)'

### ISSUE THREAD

**Issue by ortonomy** [chriscamargo/framer-viewNavigationController#8]
```
# import view controller
{ViewNavigationController} = require "ViewNavigationController"

# set up view controller
vnc = new ViewNavigationController

# set up views
titleView = new Layer
    name: "initialView"
    width: Screen.width
    height: Screen.height
    parent: vnc
lfView = new ScrollComponent
    name: "lfView"
    width: Screen.width
    height: Screen.height
    parent: vnc

# remove all back buttons from views
vnc.removeBackButton(lfView)
```

Framer throws errror `TypeError: undefined is not an object (evaluating 'view.subLayersByName(BACKBUTTON_VIEW_NAME)[0].visible = false')`

Any ideas? am I not allowed to use Scroll Components as views?

using: Framer v72

I can confirm the same happens using the demo code in `readme.md` too

**Comment by ortonomy** [comment]
From what I can tell Framer is not recognising 'vnc-backButton' as a valid sub layer in my viewController layers.

It just says they're `undefined`?!

**Comment by chriscamargo** [comment]
Thanks for reporting this @geligelu. I'm seeing that as well. I'll look into this.

In the meantime, an alternative to this method is setting the `backButton` property of your view to `false` after creation.

In your case, try placing this line after your definition of `lfView`:

`lfView.backButton = false`

**Comment by chriscamargo** [comment]
@geligelu - This should be fixed in the latest release. Thanks again for reporting!

**Comment by ortonomy** [comment]
@chriscamargo - thanks very much for making the fix. Such a useful module.
